//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movie_Ticket_Booking_Client.TheaterServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Theater", Namespace="http://schemas.datacontract.org/2004/07/Movie_Ticket_Booking_Services.Models")]
    [System.SerializableAttribute()]
    public partial class Theater : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Movie_Ticket_Booking_Client.TheaterServices.TheaterMovie[] MoviesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Theater_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Movie_Ticket_Booking_Client.TheaterServices.TheaterMovie[] Movies {
            get {
                return this.MoviesField;
            }
            set {
                if ((object.ReferenceEquals(this.MoviesField, value) != true)) {
                    this.MoviesField = value;
                    this.RaisePropertyChanged("Movies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Theater_Id {
            get {
                return this.Theater_IdField;
            }
            set {
                if ((this.Theater_IdField.Equals(value) != true)) {
                    this.Theater_IdField = value;
                    this.RaisePropertyChanged("Theater_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TheaterMovie", Namespace="http://schemas.datacontract.org/2004/07/Movie_Ticket_Booking_Services.Models")]
    [System.SerializableAttribute()]
    public partial class TheaterMovie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Movie_Ticket_Booking_Client.TheaterServices.Movie MovieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Movie_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Movie_Ticket_Booking_Client.TheaterServices.Theater TheaterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Theater_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Total_SeatsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Movie_Ticket_Booking_Client.TheaterServices.Movie Movie {
            get {
                return this.MovieField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieField, value) != true)) {
                    this.MovieField = value;
                    this.RaisePropertyChanged("Movie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Movie_Id {
            get {
                return this.Movie_IdField;
            }
            set {
                if ((this.Movie_IdField.Equals(value) != true)) {
                    this.Movie_IdField = value;
                    this.RaisePropertyChanged("Movie_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Movie_Ticket_Booking_Client.TheaterServices.Theater Theater {
            get {
                return this.TheaterField;
            }
            set {
                if ((object.ReferenceEquals(this.TheaterField, value) != true)) {
                    this.TheaterField = value;
                    this.RaisePropertyChanged("Theater");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Theater_Id {
            get {
                return this.Theater_IdField;
            }
            set {
                if ((this.Theater_IdField.Equals(value) != true)) {
                    this.Theater_IdField = value;
                    this.RaisePropertyChanged("Theater_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Total_Seats {
            get {
                return this.Total_SeatsField;
            }
            set {
                if ((this.Total_SeatsField.Equals(value) != true)) {
                    this.Total_SeatsField = value;
                    this.RaisePropertyChanged("Total_Seats");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movie", Namespace="http://schemas.datacontract.org/2004/07/Movie_Ticket_Booking_Services.Models")]
    [System.SerializableAttribute()]
    public partial class Movie : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Movie_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Release_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Movie_Ticket_Booking_Client.TheaterServices.TheaterMovie[] TheatersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genre {
            get {
                return this.GenreField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreField, value) != true)) {
                    this.GenreField = value;
                    this.RaisePropertyChanged("Genre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Movie_Id {
            get {
                return this.Movie_IdField;
            }
            set {
                if ((this.Movie_IdField.Equals(value) != true)) {
                    this.Movie_IdField = value;
                    this.RaisePropertyChanged("Movie_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Release_Date {
            get {
                return this.Release_DateField;
            }
            set {
                if ((this.Release_DateField.Equals(value) != true)) {
                    this.Release_DateField = value;
                    this.RaisePropertyChanged("Release_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Movie_Ticket_Booking_Client.TheaterServices.TheaterMovie[] Theaters {
            get {
                return this.TheatersField;
            }
            set {
                if ((object.ReferenceEquals(this.TheatersField, value) != true)) {
                    this.TheatersField = value;
                    this.RaisePropertyChanged("Theaters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TheaterServices.ITheaterServices")]
    public interface ITheaterServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITheaterServices/GetTheaters", ReplyAction="http://tempuri.org/ITheaterServices/GetTheatersResponse")]
        Movie_Ticket_Booking_Client.TheaterServices.Theater[] GetTheaters();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITheaterServices/GetTheaters", ReplyAction="http://tempuri.org/ITheaterServices/GetTheatersResponse")]
        System.Threading.Tasks.Task<Movie_Ticket_Booking_Client.TheaterServices.Theater[]> GetTheatersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITheaterServices/GetTheater", ReplyAction="http://tempuri.org/ITheaterServices/GetTheaterResponse")]
        Movie_Ticket_Booking_Client.TheaterServices.Theater GetTheater(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITheaterServices/GetTheater", ReplyAction="http://tempuri.org/ITheaterServices/GetTheaterResponse")]
        System.Threading.Tasks.Task<Movie_Ticket_Booking_Client.TheaterServices.Theater> GetTheaterAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITheaterServices/AddTheater", ReplyAction="http://tempuri.org/ITheaterServices/AddTheaterResponse")]
        string AddTheater(Movie_Ticket_Booking_Client.TheaterServices.Theater theater);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITheaterServices/AddTheater", ReplyAction="http://tempuri.org/ITheaterServices/AddTheaterResponse")]
        System.Threading.Tasks.Task<string> AddTheaterAsync(Movie_Ticket_Booking_Client.TheaterServices.Theater theater);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITheaterServices/UpdateTheater", ReplyAction="http://tempuri.org/ITheaterServices/UpdateTheaterResponse")]
        string UpdateTheater(Movie_Ticket_Booking_Client.TheaterServices.Theater theater);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITheaterServices/UpdateTheater", ReplyAction="http://tempuri.org/ITheaterServices/UpdateTheaterResponse")]
        System.Threading.Tasks.Task<string> UpdateTheaterAsync(Movie_Ticket_Booking_Client.TheaterServices.Theater theater);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITheaterServices/GetMoviesNotInTheater", ReplyAction="http://tempuri.org/ITheaterServices/GetMoviesNotInTheaterResponse")]
        Movie_Ticket_Booking_Client.TheaterServices.Movie[] GetMoviesNotInTheater(int theaterId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITheaterServices/GetMoviesNotInTheater", ReplyAction="http://tempuri.org/ITheaterServices/GetMoviesNotInTheaterResponse")]
        System.Threading.Tasks.Task<Movie_Ticket_Booking_Client.TheaterServices.Movie[]> GetMoviesNotInTheaterAsync(int theaterId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITheaterServices/DeleteTheater", ReplyAction="http://tempuri.org/ITheaterServices/DeleteTheaterResponse")]
        string DeleteTheater(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITheaterServices/DeleteTheater", ReplyAction="http://tempuri.org/ITheaterServices/DeleteTheaterResponse")]
        System.Threading.Tasks.Task<string> DeleteTheaterAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITheaterServices/AddMovieToTheater", ReplyAction="http://tempuri.org/ITheaterServices/AddMovieToTheaterResponse")]
        string AddMovieToTheater(int theaterId, int movieId, int totalSeats);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITheaterServices/AddMovieToTheater", ReplyAction="http://tempuri.org/ITheaterServices/AddMovieToTheaterResponse")]
        System.Threading.Tasks.Task<string> AddMovieToTheaterAsync(int theaterId, int movieId, int totalSeats);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITheaterServicesChannel : Movie_Ticket_Booking_Client.TheaterServices.ITheaterServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TheaterServicesClient : System.ServiceModel.ClientBase<Movie_Ticket_Booking_Client.TheaterServices.ITheaterServices>, Movie_Ticket_Booking_Client.TheaterServices.ITheaterServices {
        
        public TheaterServicesClient() {
        }
        
        public TheaterServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TheaterServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TheaterServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TheaterServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Movie_Ticket_Booking_Client.TheaterServices.Theater[] GetTheaters() {
            return base.Channel.GetTheaters();
        }
        
        public System.Threading.Tasks.Task<Movie_Ticket_Booking_Client.TheaterServices.Theater[]> GetTheatersAsync() {
            return base.Channel.GetTheatersAsync();
        }
        
        public Movie_Ticket_Booking_Client.TheaterServices.Theater GetTheater(int id) {
            return base.Channel.GetTheater(id);
        }
        
        public System.Threading.Tasks.Task<Movie_Ticket_Booking_Client.TheaterServices.Theater> GetTheaterAsync(int id) {
            return base.Channel.GetTheaterAsync(id);
        }
        
        public string AddTheater(Movie_Ticket_Booking_Client.TheaterServices.Theater theater) {
            return base.Channel.AddTheater(theater);
        }
        
        public System.Threading.Tasks.Task<string> AddTheaterAsync(Movie_Ticket_Booking_Client.TheaterServices.Theater theater) {
            return base.Channel.AddTheaterAsync(theater);
        }
        
        public string UpdateTheater(Movie_Ticket_Booking_Client.TheaterServices.Theater theater) {
            return base.Channel.UpdateTheater(theater);
        }
        
        public System.Threading.Tasks.Task<string> UpdateTheaterAsync(Movie_Ticket_Booking_Client.TheaterServices.Theater theater) {
            return base.Channel.UpdateTheaterAsync(theater);
        }
        
        public Movie_Ticket_Booking_Client.TheaterServices.Movie[] GetMoviesNotInTheater(int theaterId) {
            return base.Channel.GetMoviesNotInTheater(theaterId);
        }
        
        public System.Threading.Tasks.Task<Movie_Ticket_Booking_Client.TheaterServices.Movie[]> GetMoviesNotInTheaterAsync(int theaterId) {
            return base.Channel.GetMoviesNotInTheaterAsync(theaterId);
        }
        
        public string DeleteTheater(int id) {
            return base.Channel.DeleteTheater(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteTheaterAsync(int id) {
            return base.Channel.DeleteTheaterAsync(id);
        }
        
        public string AddMovieToTheater(int theaterId, int movieId, int totalSeats) {
            return base.Channel.AddMovieToTheater(theaterId, movieId, totalSeats);
        }
        
        public System.Threading.Tasks.Task<string> AddMovieToTheaterAsync(int theaterId, int movieId, int totalSeats) {
            return base.Channel.AddMovieToTheaterAsync(theaterId, movieId, totalSeats);
        }
    }
}
